apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: production
---
apiVersion: v1
data:
  .dockerconfigjson:
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
